import type { Metadata } from "next";
import "./globals.css";
import { heritageSans, nunito } from "./font";
import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Recco Treats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-arp=""
      className={`${heritageSans.variable} ${nunito.variable} antialiased`}
    >
      <body className={`${nunito.className} bg-transparent relative`} cz-shortcut-listen="true">
        <div className="fixed inset-0 -z-10 bg-cover bg-center bg-no-repeat"
             style={{ backgroundImage: "url('/assests/parallax.png')" }} />
        <Navbar />
        <main className="relative z-0">
          {children}
        </main>
      </body>
    </html>
  );
}
