import type { Metadata } from "next";
import "./globals.css";
import { heritageSans, nunito } from "./font";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Recco Treats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-arp=""
      className={`${heritageSans.variable} ${nunito.variable} antialiased`}
    >
      <body
        className={`${nunito.className} bg-transparent relative`}
        cz-shortcut-listen="true"
      >
        <Navbar />
        <main className="relative z-0">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
